name: Build, Register, and Deploy to AWS

on:
  push:
    branches:
      - main-test  # Adjust this as needed

jobs:
  build-register-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up AWS CLI
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      # Step 3: Log in to Amazon ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 128363281216.dkr.ecr.ap-southeast-2.amazonaws.com

      # Step 4: Build, tag, and push the Django image
      - name: Build, Tag, and Push Django Image
        run: |
          echo "Building Django image..."
          docker build -t prototype-backend ./backend
          docker tag prototype-backend:latest 128363281216.dkr.ecr.ap-southeast-2.amazonaws.com/my-django-app:latest
          echo "Pushing Django image to ECR..."
          docker push 128363281216.dkr.ecr.ap-southeast-2.amazonaws.com/my-django-app:latest

      # Step 5: Build, tag, and push the React image
      - name: Build, Tag, and Push React Image
        run: |
          echo "Building React image..."
          docker build -t prototype-frontend ./frontend
          docker tag prototype-frontend:latest 128363281216.dkr.ecr.ap-southeast-2.amazonaws.com/my-react-app:latest
          echo "Pushing React image to ECR..."
          docker push 128363281216.dkr.ecr.ap-southeast-2.amazonaws.com/my-react-app:latest

      # Step 6: Register the task definition for Django app
      - name: Register Django Task Definition
        run: |
          echo "Registering task definition for Django app..."
          cat <<EOF > django-task-definition.json
          {
            "family": "my-django-task",
            "containerDefinitions": [
              {
                "name": "my-django-container",
                "image": "128363281216.dkr.ecr.ap-southeast-2.amazonaws.com/my-django-app:latest",
                "memory": 512,
                "cpu": 256,
                "essential": true,
                "portMappings": [
                  {
                    "containerPort": 8000,
                    "hostPort": 8000
                  }
                ],
                "logConfiguration": {
                  "logDriver": "awslogs",
                  "options": {
                    "awslogs-group": "/ecs/my-django-service",
                    "awslogs-region": "ap-southeast-2",
                    "awslogs-stream-prefix": "django"
                  }
                }
              }
            ]
          }
          EOF
          aws ecs register-task-definition --cli-input-json file://django-task-definition.json --region ap-southeast-2

      # Step 7: Register the task definition for React app
      - name: Register React Task Definition
        run: |
          echo "Registering task definition for React app..."
          cat <<EOF > react-task-definition.json
          {
            "family": "my-react-task",
            "containerDefinitions": [
              {
                "name": "my-react-container",
                "image": "128363281216.dkr.ecr.ap-southeast-2.amazonaws.com/my-react-app:latest",
                "memory": 512,
                "cpu": 256,
                "essential": true,
                "portMappings": [
                  {
                    "containerPort": 80,
                    "hostPort": 80
                  }
                ],
                "logConfiguration": {
                  "logDriver": "awslogs",
                  "options": {
                    "awslogs-group": "/ecs/my-react-service",
                    "awslogs-region": "ap-southeast-2",
                    "awslogs-stream-prefix": "react"
                  }
                }
              }
            ]
          }
          EOF
          aws ecs register-task-definition --cli-input-json file://react-task-definition.json --region ap-southeast-2

      # Step 8: Check and create the Django service if it does not exist
      - name: Create Django Service if Not Exists
        run: |
          SERVICE_EXISTS=$(aws ecs describe-services --cluster auto_deployment_test_cluster --services my-django-service --region ap-southeast-2 --query 'failures[0]' | grep -c "MISSING")
          if [ "$SERVICE_EXISTS" -eq 1 ]; then
            echo "Django service does not exist. Creating service..."
            aws ecs create-service --cluster auto_deployment_test_cluster --service-name my-django-service --task-definition my-django-task --desired-count 1 --launch-type EC2 --region ap-southeast-2
          else
            echo "Django service exists."
          fi

      # Step 9: Check and create the React service if it does not exist
      - name: Create React Service if Not Exists
        run: |
          SERVICE_EXISTS=$(aws ecs describe-services --cluster auto_deployment_test_cluster --services my-react-service --region ap-southeast-2 --query 'failures[0]' | grep -c "MISSING")
          if [ "$SERVICE_EXISTS" -eq 1 ]; then
            echo "React service does not exist. Creating service..."
            aws ecs create-service --cluster auto_deployment_test_cluster --service-name my-react-service --task-definition my-react-task --desired-count 1 --launch-type EC2 --region ap-southeast-2
          else
            echo "React service exists."
          fi

      # Step 10: Deploy to ECS
      - name: Deploy to Amazon ECS
        run: |
          echo "Deploying Django service..."
          aws ecs update-service --cluster auto_deployment_test_cluster --service my-django-service --force-new-deployment --region ap-southeast-2
          echo "Deploying React service..."
          aws ecs update-service --cluster auto_deployment_test_cluster --service my-react-service --force-new-deployment --region ap-southeast-2