name: Build, Register, and Deploy to AWS ECS

on:
  push:
    branches:
      - main  # Adjust this as needed

jobs:
  build-register-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 5

      - name: Find Modified Directories
        id: check_changes
        run: |
          # Fetch the latest commit
          git fetch origin main
          changed_dirs=""

          # Loop through all directories starting with "client"
          for dir in client*; do
            if [ -d "$dir" ]; then  # Check if directory exists
              if git diff --quiet HEAD^ HEAD -- "$dir"; then
                echo "$dir was not changed"
              else
                echo "$dir was changed"
                changed_dirs="$dir"
              fi
            fi
          done

          echo "CHANGED_DIRS=$changed_dirs" >> $GITHUB_ENV

      - name: Output Changed Directories
        run: | 
          echo "Changed directories: ${{ env.CHANGED_DIRS }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Check if ECR Repository Exists and Create if Not
        id: create_ecr_repo
        shell: bash
        run: |
          REPO_NAME=${{ env.CHANGED_DIRS }}  # Replace with your desired repository name
          REGION="ap-southeast-2"  # Default region if not set in secrets

          # Check if the repository exists
          EXISTING_REPO=$(aws ecr describe-repositories --repository-names "$REPO_NAME" --query "repositories[0].repositoryName" --output text 2>/dev/null || true)

          if [ "$EXISTING_REPO" != "$REPO_NAME" ]; then
            echo "Repository '$REPO_NAME' does not exist. Creating..."
            aws ecr create-repository --repository-name "$REPO_NAME"
            echo "Repository '$REPO_NAME' created successfully."
          else
            echo "Repository '$REPO_NAME' already exists."
          fi

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 128363281216.dkr.ecr.ap-southeast-2.amazonaws.com
      
      - name: Build, Tag, and Push Django Image
        run: |
          echo "Building Django image..."
          docker build -t prototype-backend ./${{ env.CHANGED_DIRS }}/backend
          docker tag prototype-backend:latest 128363281216.dkr.ecr.ap-southeast-2.amazonaws.com/${{ env.CHANGED_DIRS }}-django-app:latest
          echo "Pushing Django image to ECR..."
          docker push 128363281216.dkr.ecr.ap-southeast-2.amazonaws.com/${{ env.CHANGED_DIRS }}-django-app:latest